export const TitleConfig = {
    dashboard : "Dashboard",
    jenisPermohonan : "Jenis Permohonan",
    jenisDokumenPerjalanan : "Jenis Dokumen Perjalanan",
    jenisDokumen : "Jenis Dokumen",
    alasanDokumenPerjalanan : "Alasan Dokumen Perjalanan",
    statusSipil : "Status Sipil",
    kewarganegaraan : "Kewarganegaraan",
    bank : "Bank",
    alasanPembatalan : "Alasan Pembatalan",
    persyaratanPengajuan : "Persyaratan Pengajuan",
    masaBerlaku : "Masa Berlaku",
    manajemenKanim : "Manajemen Kanim",
    approval : "Approval",
    approvalDetail : "Approval Detail",
    notifikasi : "Notifikasi",
    notifikasiDetail : "Notifikasi Detail",
    dpriPermohonan : "Permohonan",
    dpriPembayaran : "Pembayaran",
    dpriAlokasi : "Alokasi",
    dpriAlokasiDetail : "Alokasi Detail",
    dpriPencetakan : "Pencetakan",
    dpriPenyerahan : "Penyerahan",
    dpriPenyerahanDetail : "Penyerahan Edit",
    dpriPembatalan : "Pembatalan",
    splpPermohonan : "Permohonan",
    splpAlokasi : "Alokasi"
}

export const RouterUrl = {

    jenisPermohonan: 'dataconfig/jenis-permohonan',
    jenisDokumenPerjalanan: 'dataconfig/jenis-dokumen-perjalanan',
    jenisDokumen: 'dataconfig/jenis-dokumen',
    alasanDokumenPerjalanan: 'dataconfig/alasan-dokumen-perjalanan',
    statusSipil: 'dataconfig/status-sipil',
    kewarganegaraan: 'dataconfig/kewarganegaraan',
    bank: 'dataconfig/bank',
    alasanPembatalan: 'dataconfig/alasan-pembatalan',
    persyaratanPengajuan: 'dataconfig/persyaratan-pengajuan',
    masaBerlaku: 'dataconfig/masa-berlaku',
    manajemenKanim: 'dataconfig/manajemen-kanim',
    tambahJenisPermohonan: 'dataconfig/jenis-permohonan/tambah',
    tambahJenisDokumenPerjalanan: 'dataconfig/jenis-dokumen-perjalanan/tambah',
    editJenisDokumenPerjalanan: 'dataconfig/edit-jenis-dokumen-perjalanan/edit',
    tambahJenisDokumen: 'dataconfig/jenis-dokumen/tambah',
    tambahAlasanDokumenPerjalanan: 'dataconfig/alasan-dokumen-perjalanan/tambah',
    tambahStatusSipil: 'dataconfig/status-sipil/tambah',
    tambahKewarganegaraan: 'dataconfig/kewarganegaraan/tambah',
    tambahBank: 'dataconfig/bank/tambah',
    tambahAlasanPembatalan: 'dataconfig/alasan-pembatalan/tambah',
    tambahPersyaratanPengajuan: 'dataconfig/persyaratan-pengajuan/tambah',
    tambahMasaBerlaku: 'dataconfig/masa-berlaku/tambah',
    tambahManajemenKanim: 'dataconfig/manajemen-kanim/tambah',
    editAlasanDokumenPerjalanan: 'dataconfig/alasan-dokumen-perjalanan/edit',
    notifikasi: 'notifikasi',
    approval: 'approval',
    notifikasiDetail: 'notifikasi/detail',
    approvalDetail: 'approval/detail',
    dpriPermohonan: 'dpri/permohonan',
    dpriAlokasi: 'dpri/alokasi',
    dpriPembayaran: 'dpri/pembayaran',
    dpriPencetakan: 'dpri/pencetakan',
    dpriPenyerahan: 'dpri/penyerahan',
    dpriPembatalan: 'dpri/pembatalan',
    dpriAlokasiDetail: 'dpri/alokasi/detail',
    dpriPenyerahanDetail: 'dpri/penyerahan/detail',
    splpAlokasi:'splp/splp-alokasi',
    splpPermohonan:'splp/splp-permohonan'

}
